### ISSUE TITLE
Research FTDI serial interface

### ISSUE THREAD

**Issue by irwineffect** [PalouseRobosub/robosub_legacy#54]
## Background

Currently we use the generic VCP interface/drivers to communicate with our FTDI chips. However, FTDI has a specialized driver and associated programming interface for their chips. This has the potential to be more efficient and lower latency than our current implementation. In addition, some of our FTDI chips can speak I2C natively, which may eliminate the need for some of our microcontrollers. 
## Task

This task is to do some initial research to learn if this is worth exploring more.

Start by looking here: http://www.ftdichip.com/Support/Documents/ProgramGuides.htm

**Comment by bkallaher** [comment]
Another option is to use the fast serial mode described on page 20 (more detail on page 39) , i2c,  jtag and others are described briefly on page 19 and in detail on page 37: http://www.ftdichip.com/Support/Documents/DataSheets/ICs/DS_FT232H.pdf

**Comment by bkallaher** [comment]
If we use the ft260 we can get both UART and i2c at the same time. UART is up to 12Mbaud and i2c is up to 3.4Mbaud!
