### ISSUE TITLE
Blue Thruster Linearization

### ISSUE THREAD

**Issue by SilentStrike** [PalouseRobosub/robosub_legacy#58]
We need to create a serialization interface for loading thruster linearization coefficients for the new thrusters.  This will take some ad-hoc testing, but you can use the spec power graphs as a baseline.

**Comment by irwineffect** [comment]
If I understand correctly, this already exists, see https://github.com/PalouseRobosub/robosub/blob/dev/src/movement/ThrusterBlueESC.cpp#L169
