### ISSUE TITLE
Create an NCurses Command Line Data GUI

### ISSUE THREAD

**Issue by ryan-summers** [PalouseRobosub/robosub_legacy#62]
Currently, our implementation for looking at data can be buggy and tedious. With the use of NCurses, a simple and lightweight method to view data can be made entirely on the command line. This will simplify SSHing and use cases, as it will remove the requirement of installing Qt for the control GUI. Additionally, it simplifies the process of expanding functionality of the GUI and makes the data view fit much more easily onto screens. The current implementation is bulky and shows a lot of unnecessary data to the user on a single page.
Make an NCurses GUI that allows the user to select what data they would like to view and organize relevant data onto different, selectable views.

**Comment by SilentStrike** [comment]
The only GUI that needs to run locally is helm because it accesses shared memory.  Why rewrite a tool when it already works just fine?  Qt can fit fin, you just need to setup layouts properly.
